REWARDS_SCALING = {
    "base_penalty": -0.02,
    "no_movement_penalty": -0.1,
    "stand_in_mist_penalty": -1.0,
    "stand_in_fire_penalty": -2.0,
    "stand_in_cut_penalty": -3.0,
    "menhir_away_penalty": -0.1,
    "menhir_closer_reward": 0.1,
    "exploration_reward": 0.5,
    "tactical_attack_reward": 1.0,
    "enemy_seen_reward": 0.1,
    "weapon_pickup_reward": 0.5,
    "health_up_reward": 1.0,
    "health_down_penalty": -1.0,
    "mid_rewards_multiplier": 2.0,
    "final_score_multiplier": 15.0,
}