REWARDS_SCALING = {
    "base_penalty": -0.02,
    "no_movement_penalty": 0.0,       
    "health_up_reward": 1.0,
    "health_down_penalty": -3.0,      
    "stand_in_mist_penalty": -1.0,
    "stand_in_fire_penalty": -3.0,
    "stand_in_cut_penalty": -5.0,
    "menhir_away_penalty": -0.3,      
    "menhir_closer_reward": 0.1,      
    "tactical_attack_reward": 1.2,    
    "enemy_seen_reward": 0.15,        
    "exploration_reward": 0.2,        
    "weapon_pickup_reward": 2.0,      
    "mid_rewards_multiplier": 2.0,
    "final_score_multiplier": 20.0,   
}