from enum import Enum


class QuartersRelation(Enum):
    THE_SAME_QUARTER = 0
    OPPOSITE_QUARTERS = 1
    NEIGHBOR_QUARTERS = 2


class MenhirToCentreDistance(Enum):
    CLOSE = 0
    MODERATE = 1
    FAR = 2


class Actions(Enum):
    HIDE_IN_THE_STARTING_QUARTER = 0
    HIDE_IN_THE_OPPOSITE_QUARTER = 1
    HIDE_IN_THE_NEIGHBOR_QUARTER_HORIZONTAL = 2
    HIDE_IN_THE_NEIGHBOR_QUARTER_VERTICAL = 3


MODEL = {'fisher_island': {
    'Q': {
        ((QuartersRelation.THE_SAME_QUARTER, MenhirToCentreDistance.CLOSE),
         Actions.HIDE_IN_THE_STARTING_QUARTER): 1.1558624896695884,
        ((QuartersRelation.THE_SAME_QUARTER, MenhirToCentreDistance.CLOSE), Actions.HIDE_IN_THE_OPPOSITE_QUARTER): 0.0,
        ((QuartersRelation.THE_SAME_QUARTER, MenhirToCentreDistance.CLOSE),
         Actions.HIDE_IN_THE_NEIGHBOR_QUARTER_HORIZONTAL): 1.0001930950893358,
        ((QuartersRelation.THE_SAME_QUARTER, MenhirToCentreDistance.CLOSE),
         Actions.HIDE_IN_THE_NEIGHBOR_QUARTER_VERTICAL): -0.1495837283438684,
        ((QuartersRelation.THE_SAME_QUARTER, MenhirToCentreDistance.MODERATE),
         Actions.HIDE_IN_THE_STARTING_QUARTER): 1.1569367225829825,
        ((QuartersRelation.THE_SAME_QUARTER, MenhirToCentreDistance.MODERATE),
         Actions.HIDE_IN_THE_OPPOSITE_QUARTER): -0.2293000342155965,
        ((QuartersRelation.THE_SAME_QUARTER, MenhirToCentreDistance.MODERATE),
         Actions.HIDE_IN_THE_NEIGHBOR_QUARTER_HORIZONTAL): 0.9571024787124381,
        ((QuartersRelation.THE_SAME_QUARTER, MenhirToCentreDistance.MODERATE),
         Actions.HIDE_IN_THE_NEIGHBOR_QUARTER_VERTICAL): 0.18300100199644037,
        ((QuartersRelation.THE_SAME_QUARTER, MenhirToCentreDistance.FAR),
         Actions.HIDE_IN_THE_STARTING_QUARTER): 0.7144430518269944,
        ((QuartersRelation.THE_SAME_QUARTER, MenhirToCentreDistance.FAR),
         Actions.HIDE_IN_THE_OPPOSITE_QUARTER): -0.03955772906591605,
        ((QuartersRelation.THE_SAME_QUARTER, MenhirToCentreDistance.FAR),
         Actions.HIDE_IN_THE_NEIGHBOR_QUARTER_HORIZONTAL): 0.9715156902468686,
        ((QuartersRelation.THE_SAME_QUARTER, MenhirToCentreDistance.FAR),
         Actions.HIDE_IN_THE_NEIGHBOR_QUARTER_VERTICAL): 0.0,
        ((QuartersRelation.OPPOSITE_QUARTERS, MenhirToCentreDistance.CLOSE),
         Actions.HIDE_IN_THE_STARTING_QUARTER): 0.40455006016498796,
        ((QuartersRelation.OPPOSITE_QUARTERS, MenhirToCentreDistance.CLOSE),
         Actions.HIDE_IN_THE_OPPOSITE_QUARTER): 0.040480699687418555,
        ((QuartersRelation.OPPOSITE_QUARTERS, MenhirToCentreDistance.CLOSE),
         Actions.HIDE_IN_THE_NEIGHBOR_QUARTER_HORIZONTAL): -0.36511393040460294,
        ((QuartersRelation.OPPOSITE_QUARTERS, MenhirToCentreDistance.CLOSE),
         Actions.HIDE_IN_THE_NEIGHBOR_QUARTER_VERTICAL): 0.0,
        ((QuartersRelation.OPPOSITE_QUARTERS, MenhirToCentreDistance.MODERATE),
         Actions.HIDE_IN_THE_STARTING_QUARTER): 0.8973073294385583,
        ((QuartersRelation.OPPOSITE_QUARTERS, MenhirToCentreDistance.MODERATE),
         Actions.HIDE_IN_THE_OPPOSITE_QUARTER): 0.12561056916568983,
        ((QuartersRelation.OPPOSITE_QUARTERS, MenhirToCentreDistance.MODERATE),
         Actions.HIDE_IN_THE_NEIGHBOR_QUARTER_HORIZONTAL): 0.506298588086245,
        ((QuartersRelation.OPPOSITE_QUARTERS, MenhirToCentreDistance.MODERATE),
         Actions.HIDE_IN_THE_NEIGHBOR_QUARTER_VERTICAL): 0.0,
        ((QuartersRelation.OPPOSITE_QUARTERS, MenhirToCentreDistance.FAR),
         Actions.HIDE_IN_THE_STARTING_QUARTER): 1.1725864315705448,
        ((QuartersRelation.OPPOSITE_QUARTERS, MenhirToCentreDistance.FAR),
         Actions.HIDE_IN_THE_OPPOSITE_QUARTER): -0.25797081474866707,
        ((QuartersRelation.OPPOSITE_QUARTERS, MenhirToCentreDistance.FAR),
         Actions.HIDE_IN_THE_NEIGHBOR_QUARTER_HORIZONTAL): 0.29124779063051937,
        ((QuartersRelation.OPPOSITE_QUARTERS, MenhirToCentreDistance.FAR),
         Actions.HIDE_IN_THE_NEIGHBOR_QUARTER_VERTICAL): 0.0,
        ((QuartersRelation.NEIGHBOR_QUARTERS, MenhirToCentreDistance.CLOSE),
         Actions.HIDE_IN_THE_STARTING_QUARTER): 1.4857661914295937,
        ((QuartersRelation.NEIGHBOR_QUARTERS, MenhirToCentreDistance.CLOSE),
         Actions.HIDE_IN_THE_OPPOSITE_QUARTER): 0.3429725180135444,
        ((QuartersRelation.NEIGHBOR_QUARTERS, MenhirToCentreDistance.CLOSE),
         Actions.HIDE_IN_THE_NEIGHBOR_QUARTER_HORIZONTAL): 0.5741642531012375,
        ((QuartersRelation.NEIGHBOR_QUARTERS, MenhirToCentreDistance.CLOSE),
         Actions.HIDE_IN_THE_NEIGHBOR_QUARTER_VERTICAL): 0.3864055291286844,
        ((QuartersRelation.NEIGHBOR_QUARTERS, MenhirToCentreDistance.MODERATE),
         Actions.HIDE_IN_THE_STARTING_QUARTER): 0.8532993983283826,
        ((QuartersRelation.NEIGHBOR_QUARTERS, MenhirToCentreDistance.MODERATE),
         Actions.HIDE_IN_THE_OPPOSITE_QUARTER): 0.26075213364838423,
        ((QuartersRelation.NEIGHBOR_QUARTERS, MenhirToCentreDistance.MODERATE),
         Actions.HIDE_IN_THE_NEIGHBOR_QUARTER_HORIZONTAL): 0.9373201297204855,
        ((QuartersRelation.NEIGHBOR_QUARTERS, MenhirToCentreDistance.MODERATE),
         Actions.HIDE_IN_THE_NEIGHBOR_QUARTER_VERTICAL): 0.10156792451895551,
        ((QuartersRelation.NEIGHBOR_QUARTERS, MenhirToCentreDistance.FAR),
         Actions.HIDE_IN_THE_STARTING_QUARTER): 0.4377698183983499,
        ((QuartersRelation.NEIGHBOR_QUARTERS, MenhirToCentreDistance.FAR),
         Actions.HIDE_IN_THE_OPPOSITE_QUARTER): 0.008080915282972223,
        ((QuartersRelation.NEIGHBOR_QUARTERS, MenhirToCentreDistance.FAR),
         Actions.HIDE_IN_THE_NEIGHBOR_QUARTER_HORIZONTAL): 0.6250133359174023,
        ((QuartersRelation.NEIGHBOR_QUARTERS, MenhirToCentreDistance.FAR),
         Actions.HIDE_IN_THE_NEIGHBOR_QUARTER_VERTICAL): -0.027502190076482705},
    'state': None, 'action': None, 'reward': None, 'reward_sum': 0,
    'attempt_no': 0, 'alpha': 0.0, 'epsilon': 0.0,
    'discount_factor': 0.0
},
    'archipelago': {'Q': {
        ((QuartersRelation.THE_SAME_QUARTER, MenhirToCentreDistance.CLOSE),
         Actions.HIDE_IN_THE_STARTING_QUARTER): 0.41212851489922236,
        ((QuartersRelation.THE_SAME_QUARTER, MenhirToCentreDistance.CLOSE),
         Actions.HIDE_IN_THE_OPPOSITE_QUARTER): -0.31026675582998514,
        ((QuartersRelation.THE_SAME_QUARTER, MenhirToCentreDistance.CLOSE),
         Actions.HIDE_IN_THE_NEIGHBOR_QUARTER_HORIZONTAL): -0.29597419134528213,
        ((QuartersRelation.THE_SAME_QUARTER, MenhirToCentreDistance.CLOSE),
         Actions.HIDE_IN_THE_NEIGHBOR_QUARTER_VERTICAL): -0.15719004856916208,
        ((QuartersRelation.THE_SAME_QUARTER, MenhirToCentreDistance.MODERATE),
         Actions.HIDE_IN_THE_STARTING_QUARTER): 0.6914449914942686,
        ((QuartersRelation.THE_SAME_QUARTER, MenhirToCentreDistance.MODERATE),
         Actions.HIDE_IN_THE_OPPOSITE_QUARTER): 0.28617458602558393,
        ((QuartersRelation.THE_SAME_QUARTER, MenhirToCentreDistance.MODERATE),
         Actions.HIDE_IN_THE_NEIGHBOR_QUARTER_HORIZONTAL): 0.16282443534804875,
        ((QuartersRelation.THE_SAME_QUARTER, MenhirToCentreDistance.MODERATE),
         Actions.HIDE_IN_THE_NEIGHBOR_QUARTER_VERTICAL): 0.0,
        ((QuartersRelation.THE_SAME_QUARTER, MenhirToCentreDistance.FAR),
         Actions.HIDE_IN_THE_STARTING_QUARTER): -0.45683368279589853,
        ((QuartersRelation.THE_SAME_QUARTER, MenhirToCentreDistance.FAR),
         Actions.HIDE_IN_THE_OPPOSITE_QUARTER): -0.44011391134891603,
        ((QuartersRelation.THE_SAME_QUARTER, MenhirToCentreDistance.FAR),
         Actions.HIDE_IN_THE_NEIGHBOR_QUARTER_HORIZONTAL): -0.39559543113216944,
        ((QuartersRelation.THE_SAME_QUARTER, MenhirToCentreDistance.FAR),
         Actions.HIDE_IN_THE_NEIGHBOR_QUARTER_VERTICAL): -0.4801358483591724,
        ((QuartersRelation.OPPOSITE_QUARTERS, MenhirToCentreDistance.CLOSE),
         Actions.HIDE_IN_THE_STARTING_QUARTER): -0.29996862929566237,
        ((QuartersRelation.OPPOSITE_QUARTERS, MenhirToCentreDistance.CLOSE),
         Actions.HIDE_IN_THE_OPPOSITE_QUARTER): 0.0,
        ((QuartersRelation.OPPOSITE_QUARTERS, MenhirToCentreDistance.CLOSE),
         Actions.HIDE_IN_THE_NEIGHBOR_QUARTER_HORIZONTAL): 0.10585929750623407,
        ((QuartersRelation.OPPOSITE_QUARTERS, MenhirToCentreDistance.CLOSE),
         Actions.HIDE_IN_THE_NEIGHBOR_QUARTER_VERTICAL): -0.32960496095982594,
        ((QuartersRelation.OPPOSITE_QUARTERS, MenhirToCentreDistance.MODERATE),
         Actions.HIDE_IN_THE_STARTING_QUARTER): -0.16114912133357945,
        ((QuartersRelation.OPPOSITE_QUARTERS, MenhirToCentreDistance.MODERATE),
         Actions.HIDE_IN_THE_OPPOSITE_QUARTER): -0.7182681365671301,
        ((QuartersRelation.OPPOSITE_QUARTERS, MenhirToCentreDistance.MODERATE),
         Actions.HIDE_IN_THE_NEIGHBOR_QUARTER_HORIZONTAL): 0.0032762122030403785,
        ((QuartersRelation.OPPOSITE_QUARTERS, MenhirToCentreDistance.MODERATE),
         Actions.HIDE_IN_THE_NEIGHBOR_QUARTER_VERTICAL): -0.35423776701378007,
        ((QuartersRelation.OPPOSITE_QUARTERS, MenhirToCentreDistance.FAR),
         Actions.HIDE_IN_THE_STARTING_QUARTER): 0.4261795818191951,
        ((QuartersRelation.OPPOSITE_QUARTERS, MenhirToCentreDistance.FAR),
         Actions.HIDE_IN_THE_OPPOSITE_QUARTER): -0.010186854531850476,
        ((QuartersRelation.OPPOSITE_QUARTERS, MenhirToCentreDistance.FAR),
         Actions.HIDE_IN_THE_NEIGHBOR_QUARTER_HORIZONTAL): 0.21383059532878285,
        ((QuartersRelation.OPPOSITE_QUARTERS, MenhirToCentreDistance.FAR),
         Actions.HIDE_IN_THE_NEIGHBOR_QUARTER_VERTICAL): -0.3970338646588023,
        ((QuartersRelation.NEIGHBOR_QUARTERS, MenhirToCentreDistance.CLOSE),
         Actions.HIDE_IN_THE_STARTING_QUARTER): 0.5571946206969992,
        ((QuartersRelation.NEIGHBOR_QUARTERS, MenhirToCentreDistance.CLOSE),
         Actions.HIDE_IN_THE_OPPOSITE_QUARTER): -0.533869041610294,
        ((QuartersRelation.NEIGHBOR_QUARTERS, MenhirToCentreDistance.CLOSE),
         Actions.HIDE_IN_THE_NEIGHBOR_QUARTER_HORIZONTAL): -0.394865625609742,
        ((QuartersRelation.NEIGHBOR_QUARTERS, MenhirToCentreDistance.CLOSE),
         Actions.HIDE_IN_THE_NEIGHBOR_QUARTER_VERTICAL): -0.029808248617883233,
        ((QuartersRelation.NEIGHBOR_QUARTERS, MenhirToCentreDistance.MODERATE),
         Actions.HIDE_IN_THE_STARTING_QUARTER): 0.6098009230052801,
        ((QuartersRelation.NEIGHBOR_QUARTERS, MenhirToCentreDistance.MODERATE),
         Actions.HIDE_IN_THE_OPPOSITE_QUARTER): 0.04597870314981637,
        ((QuartersRelation.NEIGHBOR_QUARTERS, MenhirToCentreDistance.MODERATE),
         Actions.HIDE_IN_THE_NEIGHBOR_QUARTER_HORIZONTAL): -0.4505684574223888,
        ((QuartersRelation.NEIGHBOR_QUARTERS, MenhirToCentreDistance.MODERATE),
         Actions.HIDE_IN_THE_NEIGHBOR_QUARTER_VERTICAL): 0.0,
        ((QuartersRelation.NEIGHBOR_QUARTERS, MenhirToCentreDistance.FAR),
         Actions.HIDE_IN_THE_STARTING_QUARTER): 0.42691395397178017,
        ((QuartersRelation.NEIGHBOR_QUARTERS, MenhirToCentreDistance.FAR),
         Actions.HIDE_IN_THE_OPPOSITE_QUARTER): -0.6815734997038355,
        ((QuartersRelation.NEIGHBOR_QUARTERS, MenhirToCentreDistance.FAR),
         Actions.HIDE_IN_THE_NEIGHBOR_QUARTER_HORIZONTAL): 0.4400475725139257,
        ((QuartersRelation.NEIGHBOR_QUARTERS, MenhirToCentreDistance.FAR),
         Actions.HIDE_IN_THE_NEIGHBOR_QUARTER_VERTICAL): -0.22052642956471333},
        'state': None, 'action': None, 'reward': None, 'reward_sum': 0,
        'attempt_no': 0, 'alpha': 0.0, 'epsilon': 0.0,
        'discount_factor': 0.0},
    'wasteland': {'Q': {
        ((QuartersRelation.THE_SAME_QUARTER, MenhirToCentreDistance.CLOSE),
         Actions.HIDE_IN_THE_STARTING_QUARTER): 0.2734342639932196,
        ((QuartersRelation.THE_SAME_QUARTER, MenhirToCentreDistance.CLOSE),
         Actions.HIDE_IN_THE_OPPOSITE_QUARTER): 0.18034077405605192,
        ((QuartersRelation.THE_SAME_QUARTER, MenhirToCentreDistance.CLOSE),
         Actions.HIDE_IN_THE_NEIGHBOR_QUARTER_HORIZONTAL): 0.0,
        ((QuartersRelation.THE_SAME_QUARTER, MenhirToCentreDistance.CLOSE),
         Actions.HIDE_IN_THE_NEIGHBOR_QUARTER_VERTICAL): 0.0,
        ((QuartersRelation.THE_SAME_QUARTER, MenhirToCentreDistance.MODERATE),
         Actions.HIDE_IN_THE_STARTING_QUARTER): 1.4562087627612783,
        ((QuartersRelation.THE_SAME_QUARTER, MenhirToCentreDistance.MODERATE),
         Actions.HIDE_IN_THE_OPPOSITE_QUARTER): -0.040641312040178235,
        ((QuartersRelation.THE_SAME_QUARTER, MenhirToCentreDistance.MODERATE),
         Actions.HIDE_IN_THE_NEIGHBOR_QUARTER_HORIZONTAL): 0.05124516899796811,
        ((QuartersRelation.THE_SAME_QUARTER, MenhirToCentreDistance.MODERATE),
         Actions.HIDE_IN_THE_NEIGHBOR_QUARTER_VERTICAL): 0.0,
        ((QuartersRelation.THE_SAME_QUARTER, MenhirToCentreDistance.FAR),
         Actions.HIDE_IN_THE_STARTING_QUARTER): 1.747948884159485,
        ((QuartersRelation.THE_SAME_QUARTER, MenhirToCentreDistance.FAR),
         Actions.HIDE_IN_THE_OPPOSITE_QUARTER): -0.05779755514902278,
        ((QuartersRelation.THE_SAME_QUARTER, MenhirToCentreDistance.FAR),
         Actions.HIDE_IN_THE_NEIGHBOR_QUARTER_HORIZONTAL): 0.0,
        ((QuartersRelation.THE_SAME_QUARTER, MenhirToCentreDistance.FAR),
         Actions.HIDE_IN_THE_NEIGHBOR_QUARTER_VERTICAL): 0.5522448399535315,
        ((QuartersRelation.OPPOSITE_QUARTERS, MenhirToCentreDistance.CLOSE),
         Actions.HIDE_IN_THE_STARTING_QUARTER): 0.40081699257929815,
        ((QuartersRelation.OPPOSITE_QUARTERS, MenhirToCentreDistance.CLOSE),
         Actions.HIDE_IN_THE_OPPOSITE_QUARTER): 0.5932988044641193,
        ((QuartersRelation.OPPOSITE_QUARTERS, MenhirToCentreDistance.CLOSE),
         Actions.HIDE_IN_THE_NEIGHBOR_QUARTER_HORIZONTAL): 0.0,
        ((QuartersRelation.OPPOSITE_QUARTERS, MenhirToCentreDistance.CLOSE),
         Actions.HIDE_IN_THE_NEIGHBOR_QUARTER_VERTICAL): 0.0,
        ((QuartersRelation.OPPOSITE_QUARTERS, MenhirToCentreDistance.MODERATE),
         Actions.HIDE_IN_THE_STARTING_QUARTER): -0.16664802993955474,
        ((QuartersRelation.OPPOSITE_QUARTERS, MenhirToCentreDistance.MODERATE),
         Actions.HIDE_IN_THE_OPPOSITE_QUARTER): 1.1076230405443586,
        ((QuartersRelation.OPPOSITE_QUARTERS, MenhirToCentreDistance.MODERATE),
         Actions.HIDE_IN_THE_NEIGHBOR_QUARTER_HORIZONTAL): 0.0,
        ((QuartersRelation.OPPOSITE_QUARTERS, MenhirToCentreDistance.MODERATE),
         Actions.HIDE_IN_THE_NEIGHBOR_QUARTER_VERTICAL): 0.0,
        ((QuartersRelation.OPPOSITE_QUARTERS, MenhirToCentreDistance.FAR),
         Actions.HIDE_IN_THE_STARTING_QUARTER): 1.3285771294457527,
        ((QuartersRelation.OPPOSITE_QUARTERS, MenhirToCentreDistance.FAR),
         Actions.HIDE_IN_THE_OPPOSITE_QUARTER): 0.6878705624760408,
        ((QuartersRelation.OPPOSITE_QUARTERS, MenhirToCentreDistance.FAR),
         Actions.HIDE_IN_THE_NEIGHBOR_QUARTER_HORIZONTAL): 0.57059402994,
        ((QuartersRelation.OPPOSITE_QUARTERS, MenhirToCentreDistance.FAR),
         Actions.HIDE_IN_THE_NEIGHBOR_QUARTER_VERTICAL): 0.0,
        ((QuartersRelation.NEIGHBOR_QUARTERS, MenhirToCentreDistance.CLOSE),
         Actions.HIDE_IN_THE_STARTING_QUARTER): 0.9458795458961331,
        ((QuartersRelation.NEIGHBOR_QUARTERS, MenhirToCentreDistance.CLOSE),
         Actions.HIDE_IN_THE_OPPOSITE_QUARTER): 0.9809149587334178,
        ((QuartersRelation.NEIGHBOR_QUARTERS, MenhirToCentreDistance.CLOSE),
         Actions.HIDE_IN_THE_NEIGHBOR_QUARTER_HORIZONTAL): -0.11392024049543184,
        ((QuartersRelation.NEIGHBOR_QUARTERS, MenhirToCentreDistance.CLOSE),
         Actions.HIDE_IN_THE_NEIGHBOR_QUARTER_VERTICAL): 0.0,
        ((QuartersRelation.NEIGHBOR_QUARTERS, MenhirToCentreDistance.MODERATE),
         Actions.HIDE_IN_THE_STARTING_QUARTER): 1.153976598009092,
        ((QuartersRelation.NEIGHBOR_QUARTERS, MenhirToCentreDistance.MODERATE),
         Actions.HIDE_IN_THE_OPPOSITE_QUARTER): 0.6998391534411563,
        ((QuartersRelation.NEIGHBOR_QUARTERS, MenhirToCentreDistance.MODERATE),
         Actions.HIDE_IN_THE_NEIGHBOR_QUARTER_HORIZONTAL): 0.0,
        ((QuartersRelation.NEIGHBOR_QUARTERS, MenhirToCentreDistance.MODERATE),
         Actions.HIDE_IN_THE_NEIGHBOR_QUARTER_VERTICAL): 0.0,
        ((QuartersRelation.NEIGHBOR_QUARTERS, MenhirToCentreDistance.FAR),
         Actions.HIDE_IN_THE_STARTING_QUARTER): 1.726412878738499,
        ((QuartersRelation.NEIGHBOR_QUARTERS, MenhirToCentreDistance.FAR),
         Actions.HIDE_IN_THE_OPPOSITE_QUARTER): 0.7907960029485275,
        ((QuartersRelation.NEIGHBOR_QUARTERS, MenhirToCentreDistance.FAR),
         Actions.HIDE_IN_THE_NEIGHBOR_QUARTER_HORIZONTAL): 0.3694869748338285,
        ((QuartersRelation.NEIGHBOR_QUARTERS, MenhirToCentreDistance.FAR),
         Actions.HIDE_IN_THE_NEIGHBOR_QUARTER_VERTICAL): 0.5758493586140805},
        'state': None, 'action': None, 'reward': None, 'reward_sum': 0,
        'attempt_no': 0, 'alpha': 0.0, 'epsilon': 0.0,
        'discount_factor': 0.0
    },
    'dungeon': {'Q': {
        ((QuartersRelation.THE_SAME_QUARTER, MenhirToCentreDistance.CLOSE),
         Actions.HIDE_IN_THE_STARTING_QUARTER): 0.23141821505884375,
        ((QuartersRelation.THE_SAME_QUARTER, MenhirToCentreDistance.CLOSE),
         Actions.HIDE_IN_THE_OPPOSITE_QUARTER): -0.0497856204755382,
        ((QuartersRelation.THE_SAME_QUARTER, MenhirToCentreDistance.CLOSE),
         Actions.HIDE_IN_THE_NEIGHBOR_QUARTER_HORIZONTAL): 0.29120676500434584,
        ((QuartersRelation.THE_SAME_QUARTER, MenhirToCentreDistance.CLOSE),
         Actions.HIDE_IN_THE_NEIGHBOR_QUARTER_VERTICAL): 0.1766726309176201,
        ((QuartersRelation.THE_SAME_QUARTER, MenhirToCentreDistance.MODERATE),
         Actions.HIDE_IN_THE_STARTING_QUARTER): 0.7550714276008235,
        ((QuartersRelation.THE_SAME_QUARTER, MenhirToCentreDistance.MODERATE),
         Actions.HIDE_IN_THE_OPPOSITE_QUARTER): 0.3683533252594023,
        ((QuartersRelation.THE_SAME_QUARTER, MenhirToCentreDistance.MODERATE),
         Actions.HIDE_IN_THE_NEIGHBOR_QUARTER_HORIZONTAL): -0.4132199106202838,
        ((QuartersRelation.THE_SAME_QUARTER, MenhirToCentreDistance.MODERATE),
         Actions.HIDE_IN_THE_NEIGHBOR_QUARTER_VERTICAL): 0.24477121341045865,
        ((QuartersRelation.THE_SAME_QUARTER, MenhirToCentreDistance.FAR),
         Actions.HIDE_IN_THE_STARTING_QUARTER): 0.4052473812656209,
        ((QuartersRelation.THE_SAME_QUARTER, MenhirToCentreDistance.FAR),
         Actions.HIDE_IN_THE_OPPOSITE_QUARTER): -0.1873225216192859,
        ((QuartersRelation.THE_SAME_QUARTER, MenhirToCentreDistance.FAR),
         Actions.HIDE_IN_THE_NEIGHBOR_QUARTER_HORIZONTAL): 0.11090579136890444,
        ((QuartersRelation.THE_SAME_QUARTER, MenhirToCentreDistance.FAR),
         Actions.HIDE_IN_THE_NEIGHBOR_QUARTER_VERTICAL): -0.3028169363511219,
        ((QuartersRelation.OPPOSITE_QUARTERS, MenhirToCentreDistance.CLOSE),
         Actions.HIDE_IN_THE_STARTING_QUARTER): 0.009754478438583389,
        ((QuartersRelation.OPPOSITE_QUARTERS, MenhirToCentreDistance.CLOSE),
         Actions.HIDE_IN_THE_OPPOSITE_QUARTER): 0.15801006813394108,
        ((QuartersRelation.OPPOSITE_QUARTERS, MenhirToCentreDistance.CLOSE),
         Actions.HIDE_IN_THE_NEIGHBOR_QUARTER_HORIZONTAL): -0.07423447192153061,
        ((QuartersRelation.OPPOSITE_QUARTERS, MenhirToCentreDistance.CLOSE),
         Actions.HIDE_IN_THE_NEIGHBOR_QUARTER_VERTICAL): 0.0,
        ((QuartersRelation.OPPOSITE_QUARTERS, MenhirToCentreDistance.MODERATE),
         Actions.HIDE_IN_THE_STARTING_QUARTER): -0.08479385403012171,
        ((QuartersRelation.OPPOSITE_QUARTERS, MenhirToCentreDistance.MODERATE),
         Actions.HIDE_IN_THE_OPPOSITE_QUARTER): 0.057723547479276785,
        ((QuartersRelation.OPPOSITE_QUARTERS, MenhirToCentreDistance.MODERATE),
         Actions.HIDE_IN_THE_NEIGHBOR_QUARTER_HORIZONTAL): 0.0941597201615891,
        ((QuartersRelation.OPPOSITE_QUARTERS, MenhirToCentreDistance.MODERATE),
         Actions.HIDE_IN_THE_NEIGHBOR_QUARTER_VERTICAL): 0.0,
        ((QuartersRelation.OPPOSITE_QUARTERS, MenhirToCentreDistance.FAR),
         Actions.HIDE_IN_THE_STARTING_QUARTER): 0.4421239401029564,
        ((QuartersRelation.OPPOSITE_QUARTERS, MenhirToCentreDistance.FAR),
         Actions.HIDE_IN_THE_OPPOSITE_QUARTER): 0.021431046338484694,
        ((QuartersRelation.OPPOSITE_QUARTERS, MenhirToCentreDistance.FAR),
         Actions.HIDE_IN_THE_NEIGHBOR_QUARTER_HORIZONTAL): -0.2472203918653343,
        ((QuartersRelation.OPPOSITE_QUARTERS, MenhirToCentreDistance.FAR),
         Actions.HIDE_IN_THE_NEIGHBOR_QUARTER_VERTICAL): -0.40079944403466816,
        ((QuartersRelation.NEIGHBOR_QUARTERS, MenhirToCentreDistance.CLOSE),
         Actions.HIDE_IN_THE_STARTING_QUARTER): -0.08912295219062863,
        ((QuartersRelation.NEIGHBOR_QUARTERS, MenhirToCentreDistance.CLOSE),
         Actions.HIDE_IN_THE_OPPOSITE_QUARTER): 0.14331530056506428,
        ((QuartersRelation.NEIGHBOR_QUARTERS, MenhirToCentreDistance.CLOSE),
         Actions.HIDE_IN_THE_NEIGHBOR_QUARTER_HORIZONTAL): 0.20911926913838846,
        ((QuartersRelation.NEIGHBOR_QUARTERS, MenhirToCentreDistance.CLOSE),
         Actions.HIDE_IN_THE_NEIGHBOR_QUARTER_VERTICAL): -0.1237675870813869,
        ((QuartersRelation.NEIGHBOR_QUARTERS, MenhirToCentreDistance.MODERATE),
         Actions.HIDE_IN_THE_STARTING_QUARTER): 1.3027956336838291,
        ((QuartersRelation.NEIGHBOR_QUARTERS, MenhirToCentreDistance.MODERATE),
         Actions.HIDE_IN_THE_OPPOSITE_QUARTER): -0.40005165425796807,
        ((QuartersRelation.NEIGHBOR_QUARTERS, MenhirToCentreDistance.MODERATE),
         Actions.HIDE_IN_THE_NEIGHBOR_QUARTER_HORIZONTAL): 0.14993551093973476,
        ((QuartersRelation.NEIGHBOR_QUARTERS, MenhirToCentreDistance.MODERATE),
         Actions.HIDE_IN_THE_NEIGHBOR_QUARTER_VERTICAL): 0.15834532185682423,
        ((QuartersRelation.NEIGHBOR_QUARTERS, MenhirToCentreDistance.FAR),
         Actions.HIDE_IN_THE_STARTING_QUARTER): 1.4409634315943687,
        ((QuartersRelation.NEIGHBOR_QUARTERS, MenhirToCentreDistance.FAR),
         Actions.HIDE_IN_THE_OPPOSITE_QUARTER): -0.37542353520869287,
        ((QuartersRelation.NEIGHBOR_QUARTERS, MenhirToCentreDistance.FAR),
         Actions.HIDE_IN_THE_NEIGHBOR_QUARTER_HORIZONTAL): 0.11779193422027037,
        ((QuartersRelation.NEIGHBOR_QUARTERS, MenhirToCentreDistance.FAR),
         Actions.HIDE_IN_THE_NEIGHBOR_QUARTER_VERTICAL): -0.40033011057463863},
        'state': None, 'action': None, 'reward': None, 'reward_sum': 0,
        'attempt_no': 0, 'alpha': 0.0, 'epsilon': 0.0,
        'discount_factor': 0.0}
}
