from .action import Action
from .advanced_explore_action import AdvancedExploreAction
from .attack_action import AttackAction
from .attack_closest_enemy_action import AttackClosestEnemyAction
from .conquer_menhir_action import ConquerMenhirAction
from .explore_action import ExploreAction
from .go_to_action import GoToAction
from .go_to_around_action import GoToAroundAction
from .rage_attack_action import RageAttackAction
from .random_action import RandomAction
from .see_more_action import SeeMoreAction
from .sneaky_attack_action import SneakyAttackAction
from .spin_action import SpinAction
from .take_to_ones_legs_action import TakeToOnesLegsAction
